/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyBirthRelationshipsRegisterABirthRouteImport } from './routes/family-birth-relationships.register-a-birth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBirthRelationshipsRegisterABirthRoute =
  FamilyBirthRelationshipsRegisterABirthRouteImport.update({
    id: '/family-birth-relationships/register-a-birth',
    path: '/family-birth-relationships/register-a-birth',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family-birth-relationships/register-a-birth': typeof FamilyBirthRelationshipsRegisterABirthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family-birth-relationships/register-a-birth': typeof FamilyBirthRelationshipsRegisterABirthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family-birth-relationships/register-a-birth': typeof FamilyBirthRelationshipsRegisterABirthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/family-birth-relationships/register-a-birth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/family-birth-relationships/register-a-birth'
  id: '__root__' | '/' | '/family-birth-relationships/register-a-birth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyBirthRelationshipsRegisterABirthRoute: typeof FamilyBirthRelationshipsRegisterABirthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-birth-relationships/register-a-birth': {
      id: '/family-birth-relationships/register-a-birth'
      path: '/family-birth-relationships/register-a-birth'
      fullPath: '/family-birth-relationships/register-a-birth'
      preLoaderRoute: typeof FamilyBirthRelationshipsRegisterABirthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyBirthRelationshipsRegisterABirthRoute:
    FamilyBirthRelationshipsRegisterABirthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
